import = ["~/.config/alacritty/colors/iceberg-dark.toml"]
live_config_reload = true

[font]
size = 9.0

[font.bold]
family = "Iosevka"
style = "Bold"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.normal]
family = "Iosevka"
style = "Regular"

[window.padding]
x = 10
y = 10
