#!/bin/sh

# Load xresources
[ -f "$XRESOURCES" ] && xrdb -merge "$XRESOURCES"

# Autostart programs
eval "$(dbus-launch --sh-syntax --exit-with-x11)"
light -S 20 &
xsetroot -cursor_name left_ptr &
xss-lock -- xsecurelock &
pkill ssh-agent; eval "$(ssh-agent)"
dunst &
[ -n "$SVDIR" ] && runsvdir "$SVDIR" &

# Sessions
export SESSION="${1:-hlwm}"

case $SESSION in
    hlwm) exec herbstluftwm ;;
    *) exec $1 ;;
esac
