#!/bin/sh

# Load xresources
[ -f "$XRESOURCES" ] && xrdb -merge "$XRESOURCES"

# Autostart programs
light -S 20 &
sct 3500 &
xsetroot -cursor_name left_ptr &
pipewire &
pipewire-pulse &
pkill ssh-agent; eval "$(ssh-agent)"

# Sessions
export SESSION="${1:-bspwm}"

case $SESSION in
    bspwm) exec bspwm ;;
    *) exec $1 ;;
esac
