#!/bin/sh

xset_query="$(xset -q | tr -s ' ')"
xset_query="${xset_query#*Caps Lock: }"
caps_status="${xset_query%% *}"

case "$caps_status" in
    on) label='CAPSLOCK' ;;
    off) label='' ;;
esac

printf 'cpslk %s\n' "$label"
