#!/bin/sh

readonly DEV='wlp1s0'

{ 
    printf '%s\n' 'default via'; 
    ip monitor route dev "$DEV"; 
} | while read -r event; do
    case $event in
        'default via'*)
            ssid=$(iw dev $DEV info | grep 'ssid')
            ssid="${ssid#* }"
            ssid="${ssid:-Off}"
	        ;;
        'Deleted local'*) ssid='Off' ;;
        *) continue ;;
    esac

    icon='直'
    test "$ssid" = 'Off' && icon='睊'

    printf 'wifi %s\n' "$icon $ssid"
done
