#!/bin/sh

. $(command -v xresources-colors)

bspc subscribe report |
    while read -r event; do
        wks=''
        IFS=':'
        set -- ${event#?}

        while [ $# -gt 0 ]; do
            item=$1

            case $item in
                [mM]*) shift && continue ;;
                [fFoOuU]*)
                    desktop=${item#?}

                    case $item in
                        # Unactive empty desktop
                        f*) shift && continue ;;
                        # Active empty desktop
                        F*) desktop="${desktop}." ;;
                        # Unactive occupied desktop
                        o*) desktop="%{F$BLUE}$desktop%{F-}" ;;
                        # Active occupied desktop
                        O*) desktop="%{F$BLUE}${desktop}.%{F-}" ;;
                        # Urgent desktop
                        [uU]*) shift && continue ;;
                    esac

                    test -z "$wks" && wks="$wks$desktop" || wks="$wks $desktop"
                    ;;
                [LGT]*) shift && continue ;;
            esac

            shift
        done

        printf 'wks %s\n' "$wks"
    done
