local opt = vim.opt

opt.encoding = 'utf-8'
opt.clipboard = 'unnamedplus'
opt.termguicolors = true
opt.background = 'light'
opt.tabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.autoindent = true
opt.smartindent = true
opt.number = true
opt.relativenumber = true
opt.title = true
opt.splitright = true
opt.splitbelow = true
opt.wrap = false
opt.cursorline = true
opt.cursorcolumn = true
opt.ignorecase = true
opt.smartcase = true
opt.scrolloff = 5
