#!/bin/sh

. "$(command -v xresources-colors)"

# Startup programs
pgrep -x polybar || polybar top &
pgrep -x sxhkd >/dev/null || sxhkd &
read -r wall < "$HOME"/.cache/dark_theme.wallpaper && eval "$wall" &

# Desktops
bspc monitor -d 1 2 3 4 5
bspc desktop '2' -l monocle
bspc desktop '3' -l monocle

# Configs
bspc config normal_border_color "$DARK_GREY"
bspc config focused_border_color "$YELLOW"
bspc config presel_feedback_color "$CYAN"
bspc config border_width 10
bspc config window_gap 8
bspc config click_to_focus none
bspc config borderless_monocle true

# Rules
for i in 'jetbrains-idea-ce' 'jetbrains-studio' 'Java'; do
	bspc rule -a "$i" desktop=^1 follow=on focus=on
done
for i in 'Chromium' 'Chromium-devel' 'Nextcloud' 'Tor Browser' 'firefox-aurora'; do
	bspc rule -a "$i" desktop=^2 follow=on focus=on
done
for i in '*:libreoffice' '*:soffice' 'Gimp' 'Inkscape'; do
    bspc rule -a "$i" desktop=^3 follow=on focus=on;
done
bspc rule -a 'KeePassXC' desktop=^4 follow=on focus=on
bspc rule -a 'Virt-manager' desktop=^5 follow=on focus=on
bspc rule -a 'SimpleScreenRecorder' state=floating follow=on focus=on
bspc rule -a '*:*:Picture in picture' state=floating follow=on focus=off
bspc rule -a 'Sxiv' state=floating follow=on focus=on
