#!/usr/bin/env bash

# Startup programs
pkill -of "$(command -v panel)" > /dev/null; panel &
pgrep -x sxhkd > /dev/null || sxhkd &
xwallpaper --zoom $HOME/tmp/pics/wallpapers/Path.png &
battnotif &

# Desktops
bspc monitor -d 1 2 3 4 5
bspc desktop '2' -l monocle
bspc desktop '3' -l monocle

# Configs
source $(command -v colors)
source $XDG_CONFIG_HOME/lemonbar/config
padding=3

bspc config normal_border_color "$DARK_GREY"
bspc config focused_border_color "$BLUE"
bspc config presel_feedback_color "$BLUE"
bspc config border_width 2
bspc config window_gap 2
bspc config bottom_padding $(($PANEL_HEIGHT + $padding))
bspc config left_padding $padding
bspc config right_padding $padding
bspc config top_padding $padding
bspc config click_to_focus none

# Rules
web=('Chromium' 'Chromium-devel' 'Nextcloud' 'Tor Browser')
office=('*:libreoffice' '*:soffice' 'Gimp' 'Inkscape' 'Java' 'jetbrains-idea-ce' 'MuPDF')
misc=('KeePassXC' 'qt5ct')

for i in "${web[@]}"; do bspc rule -a "$i" desktop=^2 follow=on focus=on; done
for i in "${office[@]}"; do bspc rule -a "$i" desktop=^3 follow=on focus=on; done
for i in "${misc[@]}"; do bspc rule -a "$i" desktop=^4 follow=on focus=on; done
bspc rule -a 'Virt-manager' desktop=^5 follow=on focus=on
bspc rule -a 'SimpleScreenRecorder' state=floating follow=on focus=on
bspc rule -a '*:*:Picture in picture' state=floating follow=on focus=off
