#!/bin/sh

case $1 in
    "C-d") while read file; do mv -vf $file /tmp; done ;;
    "C-c") while read file; do xclip -selection clipboard -t image/png "$file"; done ;;
    "C-x") xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
esac
