#!/bin/sh

case $1 in
    'd')
        while read -r file; do
            gio trash "$file"
        done
        ;;
    'c')
        while read -r file; do
            xclip -selection clipboard -t image/png "$file";
        done
        ;;
    'M-c')
        xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard
        ;;
esac
