#!/bin/sh

. "$(command -v xresources-colors)"

{ printf '\n'; herbstclient --idle tag_changed; } | 
    while read -r _; do
        tags=$(herbstclient tag_status | tr '\t' '_')
        IFS='_'; set -- ${tags#_}

        output=''
        while [ $# -gt 0 ]; do
            tag=$1

            case $tag in
                "."*) shift && continue ;;
                ":"*) styled_tag="%{F$DARK_GREY}${tag#?}${F-}" ;;
                "#"*) styled_tag="%{F$CYAN}${tag#?}%{F-}" ;;
                "!"*) styled_tag="%{F$RED}${tag#?}%{F-}" ;;
                *) shift && continue ;;
            esac

            separator=' '
            test -z "$output" && separator=''
            output="$output$separator$styled_tag"

            shift
        done

        printf '%s\n' "$output"
    done
