#!/bin/sh

. "$(command -v xresources-colors)"

{ printf '\n'; herbstclient --idle tag; } | 
    while read -r _; do
        set -- $(herbstclient tag_status)

        output=''

        while [ $# -gt 0 ]; do
            tag=$1

            case $tag in
                .*) shift && continue ;;
                :*) styled_tag="%{F$DARK_GREY}${tag#?}%{F-}" ;;
                \#*) styled_tag="%{F$CYAN}${tag#?}%{F-}" ;;
                !*) styled_tag="%{F$RED}${tag#?}%{F-}" ;;
                *) shift && continue ;;
            esac

            styled_tag="%{A:herbstclient use ${tag#?}:}$styled_tag%{A}"

            if [ -z "$output" ]; then
                separator=''
            else
                separator=' '
            fi

            output="$output$separator$styled_tag"

            shift
        done

        printf '%s\n' "$output"
    done
