#!/bin/sh

herbstclient emit_hook reload

set -- 1st 2nd 3rd 4th 5th
total=$#

herbstclient foreach T tags.by-name. \
    sprintf ATTR_INDEX %c.index T \
    sprintf ATTR_NAME %c.name T \
    substitute VALUE_NAME ATTR_NAME \
    and . compare ATTR_INDEX gt $((total-1)) . merge_tag VALUE_NAME

while [ $# -gt 0 ]; do
    index=$((total-$#))
    new_name=$1
    old_name="$(herbstclient foreach T tags.by-name. \
        sprintf ATTR_INDEX %c.index T \
        sprintf ATTR_NAME %c.name T \
        substitute VALUE_NAME ATTR_NAME \
        and . compare ATTR_INDEX = $index . echo VALUE_NAME)"

    if [ -n "$old_name" ]; then
        herbstclient rename "$old_name" "$new_name"
    else
        herbstclient add "$new_name"
    fi

    shift
done

. "$(command -v xresources-colors)"
. "${0%/*}/bind"
. "${0%/*}/theme"
. "${0%/*}/rule"

read -r wall < "$HOME"/.cache/dark_theme.wallpaper && eval "$wall" &
pgrep -x polybar >/dev/null 2>&1 || polybar -c ~/.config/polybar/herbstluftwm &

herbstclient unlock
